openapi: 3.0.0
info:
  title: Quiz Service API
  description: Service for managing quizzes in the microservice architecture
  version: 1.0.0
  contact:
    name: Development Team
servers:
  - url: http://localhost:9005/api/v1
    description: Local development server
tags:
  - name: Quiz
    description: Operations for managing quizzes

paths:
  /quiz:
    post:
      summary: Create a new quiz
      description: Creates a new quiz with title, questions, and assigned students
      operationId: createQuiz
      tags:
        - Quiz
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuizDTO'
      responses:
        '200':
          description: Quiz created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateQuizResponse'
        '400':
          description: Bad request - validation error
          content:
            application/json:
              schema:
                type: string
                example: "Lỗi khi tạo quiz Invalid quiz configuration"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: string
                example: "Lỗi khi tạo quiz Internal server error"

components:
  schemas:
    QuizDTO:
      type: object
      description: Data for creating a new quiz
      required:
        - title
        - quizConfigId
        - questionIds
        - assignedStudentIds
      properties:
        title:
          type: string
          description: Title of the quiz
          example: "Midterm Exam - Computer Science 101"
        quizConfigId:
          type: string
          description: ID of the quiz configuration
          example: "5f8d0a1b2c3d4e5f6a7b8c9f"
        questionIds:
          type: array
          description: List of question IDs in the quiz
          items:
            type: string
          example: ["5f8d0a1b2c3d4e5f6a7b8c9g", "5f8d0a1b2c3d4e5f6a7b8c9h"]
        assignedStudentIds:
          type: array
          description: List of student IDs assigned to the quiz
          items:
            type: string
          example: ["5f8d0a1b2c3d4e5f6a7b8c9d", "5f8d0a1b2c3d4e5f6a7b8c9e"]

    CreateQuizResponse:
      type: object
      description: Response after creating a quiz
      properties:
        id:
          type: string
          description: Unique identifier of the created quiz
          example: "123e4567-e89b-12d3-a456-426614174000"
        code:
          type: string
          description: Unique code for accessing the quiz
          example: "QUIZ123"
        title:
          type: string
          description: Title of the quiz
          example: "Midterm Exam - Computer Science 101"
        studentIds:
          type: array
          description: List of student IDs assigned to the quiz
          items:
            type: string
          example: ["5f8d0a1b2c3d4e5f6a7b8c9d", "5f8d0a1b2c3d4e5f6a7b8c9e"]
        quizConfigId:
          type: string
          description: ID of the quiz configuration
          example: "5f8d0a1b2c3d4e5f6a7b8c9f"
        questionIds:
          type: array
          description: List of question IDs in the quiz
          items:
            type: string
          example: ["5f8d0a1b2c3d4e5f6a7b8c9g", "5f8d0a1b2c3d4e5f6a7b8c9h"]