server:
  port: 8888

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discover:
        locator:
          enabled: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/v1/students/**
        - id: quiz-creation-service
          uri: lb://quiz-creation-service
          predicates:
            - Path=/api/v1/quiz-creation/**

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true